/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeLib_NativeLib */

#ifndef _Included_nativeLib_NativeLib
#define _Included_nativeLib_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeLib_NativeLib
 * Method:    detectMarkers
 * Signature: ([B[FIIZ)I
 */
JNIEXPORT jint JNICALL Java_nativeLib_NativeLib_detectMarkers
  (JNIEnv *, jobject, jbyteArray, jfloatArray, jint, jint, jboolean);

/*
 * Class:     nativeLib_NativeLib
 * Method:    calibrate
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_nativeLib_NativeLib_calibrate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     nativeLib_NativeLib
 * Method:    getCalibration
 * Signature: ([D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_nativeLib_NativeLib_getCalibration
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     nativeLib_NativeLib
 * Method:    setCalibration
 * Signature: ([D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_nativeLib_NativeLib_setCalibration
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     nativeLib_NativeLib
 * Method:    initThread
 * Signature: ([I[D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_nativeLib_NativeLib_initThread
  (JNIEnv *, jobject, jintArray, jdoubleArray, jdoubleArray);
#ifdef __cplusplus
}
#endif
#endif
